# 🚪 GATEWAY = THE ACTUAL FRONT DOOR
#
# Think of it like:
# - Airport terminal (where all flights enter/exit)
# - Hotel reception desk (where all guests check in)
# - Building entrance (where all visitors enter)
#
# Gateway is the ENTRY POINT where ALL traffic comes in
# It listens on specific ports (like door numbers)
# It decides which requests are allowed in
#
# Real-world example:
# Building has main entrance on Floor 1 (port 80)
# All visitors must enter through this door
# Security at door checks: "Are you allowed in?"
#
# What happens when you create this:
# ✅ Envoy creates a proxy pod (the security guard)
# ✅ Envoy creates a service (the actual door with address)
# ✅ Now traffic can enter on port 80!

apiVersion: gateway.networking.k8s.io/v1  # Gateway API version
kind: Gateway  # Type: The actual front door for traffic
metadata:
  name: high-way  # Door name: "high-way" (you can name it "main-entrance", "api-gateway", anything!)
spec:
  gatewayClassName: eg  # Built by factory "eg" (references GatewayClass above)
  listeners:  # What doors/ports to open
    - name: http  # Door name: "http"
      protocol: HTTP  # Type of traffic: HTTP (not HTTPS/secure)
      port: 80  # Door number: 80 (like apartment number)

##under gatewayclass name is "eg" ,